"""Prior-map contracts and adapters for STRIVE."""

from .alignment import PriorMapAlignment, PriorMapAlignmentError
from .contracts import (
    FrontierPrior,
    ObjectPrior,
    PriorMapData,
    PriorObject,
    PriorObservationRecord,
    PriorRoom,
    PriorTopologyEdge,
    RoomPrior,
    SearchPriorResult,
    SupportRegionPrior,
)
from .evaluation import (
    prior_map_failure_modes,
    prior_map_metrics_fields,
    prior_map_metrics_summary,
    write_prior_map_static_artifacts,
    write_prior_map_step_artifacts,
)
from .habitat_objectnav import (
    HabitatObjectNavPriorMapBuilder,
    HabitatPriorMapBuildResult,
    build_habitat_objectnav_prior_map,
    write_prior_map_with_alignment,
)
from .hm3d_semantic import (
    HM3DSemanticInstance,
    HM3DSemanticPriorMapBuildResult,
    HM3DSemanticTxtPriorMapBuilder,
    build_hm3d_semantic_prior_map,
    write_hm3d_semantic_prior_map_with_alignment,
)
from .hm3d_groundtruth import (
    HM3DGroundTruthBuildConfig,
    HM3DGroundTruthPriorMapBuildResult,
    HM3DGroundTruthPriorMapBuilder,
    HM3DSceneAssets,
    build_hm3d_groundtruth_prior_map_from_scene_dir,
    build_hm3d_groundtruth_prior_map_from_sim,
    extract_hm3d_mesh_object_bounds,
    open_hm3d_simulator,
    write_hm3d_groundtruth_prior_map_with_alignment,
)
from .loaders import PriorMapLoader, PriorMapLoaderError
from .floorplan_layout import FloorplanLayout, FloorplanLevel, FloorplanRegion
from .hm3d_layout import (
    HM3DLayoutBuildResult,
    HM3DLayoutBuilder,
    build_hm3d_floorplan_layout_from_scene_dir,
    build_hm3d_floorplan_layout_from_sim,
    write_hm3d_floorplan_layout,
)
from .memory import PriorMapMemory, PriorObjectRuntimeState, PriorRoomRuntimeState
from .multimodal import PriorMapMultimodalContext, sha256_file, stable_payload_hash
from .room_semantics import (
    RoomEvidence,
    RoomSemanticCache,
    RoomSemanticClassifier,
    RoomSemanticResult,
    room_evidence_from_record,
)
from .high_level_selector import (
    HighLevelCandidate,
    HighLevelSelectionCache,
    HighLevelSelectionResult,
    PriorMapHighLevelSelector,
    build_runtime_candidates,
    runtime_candidate_payloads,
)
from .policy_adapter import (
    PriorAnnotatedCandidate,
    PriorMapPolicyAdapter,
    annotate_target_candidates,
    rank_frontiers,
    rank_rooms,
)
from .prompt_context import (
    PriorMapPromptContextBuilder,
    PromptContextBundle,
    summarize_prior_map,
    summarize_search_prior,
    to_compact_xml,
)
from .query import PriorMapQueryContext, PriorMapQueryService, PriorMapQueryWeights
from .real_robot import (
    PriorMapRealRobotConfig,
    PriorMapRealRobotRuntime,
    build_prior_map_real_robot_runtime,
    detect_live_prior_conflicts,
)
from .simulation import (
    PriorMapSimulationConfig,
    PriorMapSimulationRuntime,
    build_prior_map_simulation_runtime,
    configure_mapper_prior_map,
    refresh_mapper_prior_map_query,
)
from .visualizer import (
    FloorPlanOverlay,
    FloorPlanOverlayPoint,
    FloorPlanView,
    PriorMapFloorPlanVisualizer,
    PriorMapSomVisualizer,
    SomMarker,
    SomView,
    build_floorplan_overlay,
    render_floorplan_global_view,
    render_floorplan_room_view,
    render_global_view,
    render_room_view,
    write_floorplan_artifacts,
    write_som_artifacts,
)

__all__ = [
    "FrontierPrior",
    "HabitatObjectNavPriorMapBuilder",
    "HabitatPriorMapBuildResult",
    "HM3DSemanticInstance",
    "HM3DSemanticPriorMapBuildResult",
    "HM3DSemanticTxtPriorMapBuilder",
    "HM3DGroundTruthBuildConfig",
    "HM3DGroundTruthPriorMapBuildResult",
    "HM3DGroundTruthPriorMapBuilder",
    "HM3DSceneAssets",
    "ObjectPrior",
    "PriorMapAlignment",
    "PriorMapAlignmentError",
    "PriorMapLoader",
    "PriorMapLoaderError",
    "FloorplanLayout",
    "FloorplanLevel",
    "FloorplanRegion",
    "HM3DLayoutBuildResult",
    "HM3DLayoutBuilder",
    "PriorMapMemory",
    "PriorMapMultimodalContext",
    "RoomEvidence",
    "RoomSemanticCache",
    "RoomSemanticClassifier",
    "RoomSemanticResult",
    "room_evidence_from_record",
    "HighLevelCandidate",
    "HighLevelSelectionCache",
    "HighLevelSelectionResult",
    "PriorMapHighLevelSelector",
    "build_runtime_candidates",
    "runtime_candidate_payloads",
    "PriorAnnotatedCandidate",
    "PriorMapPolicyAdapter",
    "PriorMapPromptContextBuilder",
    "PriorMapQueryContext",
    "PriorMapQueryService",
    "PriorMapQueryWeights",
    "PriorMapRealRobotConfig",
    "PriorMapRealRobotRuntime",
    "PriorMapSimulationConfig",
    "PriorMapSimulationRuntime",
    "PriorMapFloorPlanVisualizer",
    "PriorMapSomVisualizer",
    "PriorMapData",
    "PriorObject",
    "PriorObjectRuntimeState",
    "PriorObservationRecord",
    "PriorRoom",
    "PriorRoomRuntimeState",
    "PriorTopologyEdge",
    "PromptContextBundle",
    "RoomPrior",
    "SearchPriorResult",
    "FloorPlanOverlay",
    "FloorPlanOverlayPoint",
    "FloorPlanView",
    "SomMarker",
    "SomView",
    "SupportRegionPrior",
    "annotate_target_candidates",
    "build_prior_map_real_robot_runtime",
    "build_prior_map_simulation_runtime",
    "build_floorplan_overlay",
    "build_habitat_objectnav_prior_map",
    "build_hm3d_semantic_prior_map",
    "build_hm3d_groundtruth_prior_map_from_scene_dir",
    "build_hm3d_groundtruth_prior_map_from_sim",
    "open_hm3d_simulator",
    "build_hm3d_floorplan_layout_from_scene_dir",
    "build_hm3d_floorplan_layout_from_sim",
    "configure_mapper_prior_map",
    "detect_live_prior_conflicts",
    "prior_map_failure_modes",
    "prior_map_metrics_fields",
    "prior_map_metrics_summary",
    "rank_frontiers",
    "rank_rooms",
    "refresh_mapper_prior_map_query",
    "render_floorplan_global_view",
    "render_floorplan_room_view",
    "render_global_view",
    "render_room_view",
    "summarize_prior_map",
    "summarize_search_prior",
    "to_compact_xml",
    "write_prior_map_static_artifacts",
    "write_prior_map_step_artifacts",
    "write_prior_map_with_alignment",
    "write_hm3d_semantic_prior_map_with_alignment",
    "write_hm3d_groundtruth_prior_map_with_alignment",
    "write_hm3d_floorplan_layout",
    "write_floorplan_artifacts",
    "write_som_artifacts",
    "sha256_file",
    "stable_payload_hash",
]
