"""Launch the STRIVE high-level instruction runtime node."""

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description():
    """Return launch description for the high-level runtime node."""

    return LaunchDescription(
        [
            DeclareLaunchArgument("instruction", default_value=""),
            DeclareLaunchArgument("object_topic", default_value="/object_nodes_list"),
            DeclareLaunchArgument("room_topic", default_value="/room_nodes_list"),
            DeclareLaunchArgument("odom_topic", default_value="/aft_mapped_to_init"),
            DeclareLaunchArgument("path_topic", default_value="/path"),
            DeclareLaunchArgument("planner_status_topic", default_value="/local_planner/status"),
            DeclareLaunchArgument("image_topic", default_value="/camera/image"),
            DeclareLaunchArgument("detection_topic", default_value="/detection_result"),
            DeclareLaunchArgument("depth_topic", default_value=""),
            DeclareLaunchArgument("pointcloud_topic", default_value=""),
            DeclareLaunchArgument("waypoint_topic", default_value="/way_point"),
            DeclareLaunchArgument("test_waypoint_topic", default_value="/strive/test_way_point"),
            DeclareLaunchArgument("motion_backend", default_value="waypoint"),
            DeclareLaunchArgument("motion_action_name", default_value="/strive/execute_waypoint"),
            DeclareLaunchArgument("controller_contract_file", default_value=""),
            DeclareLaunchArgument("hold_topic", default_value=""),
            DeclareLaunchArgument("cancel_topic", default_value=""),
            DeclareLaunchArgument("emergency_stop_topic", default_value=""),
            DeclareLaunchArgument("allow_emergency_stop_publish", default_value="false"),
            DeclareLaunchArgument("lower_controller_enabled", default_value="false"),
            DeclareLaunchArgument("world_frame", default_value="map"),
            DeclareLaunchArgument("policy_mode", default_value="wait"),
            DeclareLaunchArgument("dataset_target", default_value=""),
            DeclareLaunchArgument("instruction_plan_backend", default_value="llm"),
            DeclareLaunchArgument("vlm", default_value="cognav"),
            DeclareLaunchArgument("enable_final_verifier", default_value="false"),
            DeclareLaunchArgument("evidence_mode", default_value="auto"),
            DeclareLaunchArgument("prior_map_path", default_value=""),
            DeclareLaunchArgument("prior_map_source", default_value="auto"),
            DeclareLaunchArgument("prior_map_alignment", default_value="identity"),
            DeclareLaunchArgument("enable_prior_map_vlm", default_value="false"),
            DeclareLaunchArgument("prior_map_vlm_interval", default_value="10"),
            DeclareLaunchArgument("room_semantic_interval", default_value="10"),
            DeclareLaunchArgument("enable_room_semantics", default_value="false"),
            DeclareLaunchArgument("run_directory", default_value="/tmp/strive_real_robot_runtime"),
            DeclareLaunchArgument("decision_period_s", default_value="1.0"),
            DeclareLaunchArgument("queue_size", default_value="10"),
            DeclareLaunchArgument("use_sim_time", default_value="false"),
            DeclareLaunchArgument("dry_run", default_value="true"),
            DeclareLaunchArgument("dry_run_status", default_value="idle"),
            DeclareLaunchArgument("require_pose", default_value="true"),
            DeclareLaunchArgument("require_image", default_value="true"),
            DeclareLaunchArgument("xy_goal_tolerance_m", default_value="0.35"),
            DeclareLaunchArgument("z_goal_tolerance_m", default_value="1.0"),
            DeclareLaunchArgument("navigation_timeout_s", default_value="60.0"),
            DeclareLaunchArgument("no_progress_timeout_s", default_value="12.0"),
            DeclareLaunchArgument("min_progress_delta_m", default_value="0.05"),
            DeclareLaunchArgument("path_stale_timeout_s", default_value="5.0"),
            DeclareLaunchArgument("velocity_tolerance_mps", default_value="0.08"),
            DeclareLaunchArgument("stable_reach_time_s", default_value="0.2"),
            DeclareLaunchArgument("persist_observation_images", default_value="false"),
            DeclareLaunchArgument("observation_image_directory", default_value=""),
            Node(
                package="strive_sysnav_bringup",
                executable="strive_instruction_runtime",
                name="strive_instruction_runtime",
                output="screen",
                parameters=[
                    {
                        "instruction": LaunchConfiguration("instruction"),
                        "object_topic": LaunchConfiguration("object_topic"),
                        "room_topic": LaunchConfiguration("room_topic"),
                        "odom_topic": LaunchConfiguration("odom_topic"),
                        "path_topic": LaunchConfiguration("path_topic"),
                        "planner_status_topic": LaunchConfiguration("planner_status_topic"),
                        "image_topic": LaunchConfiguration("image_topic"),
                        "detection_topic": LaunchConfiguration("detection_topic"),
                        "depth_topic": LaunchConfiguration("depth_topic"),
                        "pointcloud_topic": LaunchConfiguration("pointcloud_topic"),
                        "waypoint_topic": LaunchConfiguration("waypoint_topic"),
                        "test_waypoint_topic": LaunchConfiguration("test_waypoint_topic"),
                        "motion_backend": LaunchConfiguration("motion_backend"),
                        "motion_action_name": LaunchConfiguration("motion_action_name"),
                        "controller_contract_file": LaunchConfiguration("controller_contract_file"),
                        "hold_topic": LaunchConfiguration("hold_topic"),
                        "cancel_topic": LaunchConfiguration("cancel_topic"),
                        "emergency_stop_topic": LaunchConfiguration("emergency_stop_topic"),
                        "allow_emergency_stop_publish": LaunchConfiguration("allow_emergency_stop_publish"),
                        "lower_controller_enabled": LaunchConfiguration("lower_controller_enabled"),
                        "world_frame": LaunchConfiguration("world_frame"),
                        "policy_mode": LaunchConfiguration("policy_mode"),
                        "dataset_target": LaunchConfiguration("dataset_target"),
                        "instruction_plan_backend": LaunchConfiguration("instruction_plan_backend"),
                        "vlm": LaunchConfiguration("vlm"),
                        "enable_final_verifier": LaunchConfiguration("enable_final_verifier"),
                        "evidence_mode": LaunchConfiguration("evidence_mode"),
                        "prior_map_path": LaunchConfiguration("prior_map_path"),
                        "prior_map_source": LaunchConfiguration("prior_map_source"),
                        "prior_map_alignment": LaunchConfiguration("prior_map_alignment"),
                        "enable_prior_map_vlm": LaunchConfiguration("enable_prior_map_vlm"),
                        "prior_map_vlm_interval": LaunchConfiguration("prior_map_vlm_interval"),
                        "room_semantic_interval": LaunchConfiguration("room_semantic_interval"),
                        "enable_room_semantics": LaunchConfiguration("enable_room_semantics"),
                        "run_directory": LaunchConfiguration("run_directory"),
                        "decision_period_s": LaunchConfiguration("decision_period_s"),
                        "queue_size": LaunchConfiguration("queue_size"),
                        "use_sim_time": LaunchConfiguration("use_sim_time"),
                        "dry_run": LaunchConfiguration("dry_run"),
                        "dry_run_status": LaunchConfiguration("dry_run_status"),
                        "require_pose": LaunchConfiguration("require_pose"),
                        "require_image": LaunchConfiguration("require_image"),
                        "xy_goal_tolerance_m": LaunchConfiguration("xy_goal_tolerance_m"),
                        "z_goal_tolerance_m": LaunchConfiguration("z_goal_tolerance_m"),
                        "navigation_timeout_s": LaunchConfiguration("navigation_timeout_s"),
                        "no_progress_timeout_s": LaunchConfiguration("no_progress_timeout_s"),
                        "min_progress_delta_m": LaunchConfiguration("min_progress_delta_m"),
                        "path_stale_timeout_s": LaunchConfiguration("path_stale_timeout_s"),
                        "velocity_tolerance_mps": LaunchConfiguration("velocity_tolerance_mps"),
                        "stable_reach_time_s": LaunchConfiguration("stable_reach_time_s"),
                        "persist_observation_images": LaunchConfiguration("persist_observation_images"),
                        "observation_image_directory": LaunchConfiguration("observation_image_directory"),
                    }
                ],
            ),
        ]
    )
