"""Real-robot interfaces for STRIVE.

The package starts with platform-independent contracts. Platform adapters
should live in sibling modules and translate ROS/SysNav/Habitat-specific data
into these contracts before invoking STRIVE planning or verification logic.
"""

from real_robot.contracts import (
    BBox2D,
    CameraFrame,
    CameraModel,
    DetectionFrame,
    EvidenceSource,
    FrontierSnapshot,
    MotionGoal,
    MotionGoalMode,
    MotionReasonCode,
    NavigationIntent,
    NavigationStatus,
    NavigationStatusCode,
    ObjectNodeSnapshot,
    Pose3D,
    QuaternionXYZW,
    RealObservation,
    RoomSnapshot,
    RuntimeDecision,
    SemanticMapSnapshot,
    Vector3,
    ViewEvidence,
    ViewpointGoal,
    ViewpointResult,
    ViewpointSnapshot,
)
from real_robot.detector_vocabulary import (
    DetectorLabelEntry,
    DetectorVocabulary,
    DetectorVocabularyAdapter,
    merge_label_provenance,
    vocabulary_context,
)
from real_robot.observation_cache import (
    ObjectCropEvidenceProvider,
    RosObservationCache,
)
from real_robot.sysnav_ros_adapters import (
    RosDetectionResultAdapter,
    RosNavigationStatusProvider,
    RosObjectNodeAdapter,
    RosRoomNodeAdapter,
    RosWaypointController,
    SysNavTopicConfig,
    build_semantic_map_snapshot,
)
from real_robot.motion_safety import SafetyDecision, SafetyState, SafetyVelocityPolicy, VelocityCommand, VelocityLimits
from real_robot.control.controller_contract import (
    ControllerContract,
    ControllerContractError,
    load_controller_contract,
    validate_controller_contract,
)
from real_robot.sysnav_runtime import (
    DryRunMotionController,
    FinalInstructionVerifierAdapter,
    FirstObjectSmokePolicy,
    LatestObservationEvidenceProvider,
    RealInstructionRuntimeState,
    RuntimeDecisionJsonlWriter,
    RuntimeReadiness,
    SysNavInstructionRuntime,
    SysNavSemanticMapBridge,
    ViewpointEvidenceLoop,
    WaitInstructionPolicy,
    runtime_decision_to_dict,
)

__all__ = [
    "BBox2D",
    "CameraFrame",
    "CameraModel",
    "DetectionFrame",
    "EvidenceSource",
    "FrontierSnapshot",
    "MotionGoal",
    "MotionGoalMode",
    "MotionReasonCode",
    "NavigationIntent",
    "NavigationStatus",
    "NavigationStatusCode",
    "ObjectNodeSnapshot",
    "Pose3D",
    "QuaternionXYZW",
    "RealObservation",
    "RoomSnapshot",
    "RuntimeDecision",
    "SemanticMapSnapshot",
    "Vector3",
    "ViewEvidence",
    "ViewpointGoal",
    "ViewpointResult",
    "ViewpointSnapshot",
    "DetectorLabelEntry",
    "DetectorVocabulary",
    "DetectorVocabularyAdapter",
    "merge_label_provenance",
    "vocabulary_context",
    "ObjectCropEvidenceProvider",
    "RosObservationCache",
    "RosDetectionResultAdapter",
    "RosNavigationStatusProvider",
    "RosObjectNodeAdapter",
    "RosRoomNodeAdapter",
    "RosWaypointController",
    "SysNavTopicConfig",
    "build_semantic_map_snapshot",
    "SafetyDecision",
    "SafetyState",
    "SafetyVelocityPolicy",
    "VelocityCommand",
    "VelocityLimits",
    "ControllerContract",
    "ControllerContractError",
    "load_controller_contract",
    "validate_controller_contract",
    "DryRunMotionController",
    "FinalInstructionVerifierAdapter",
    "FirstObjectSmokePolicy",
    "LatestObservationEvidenceProvider",
    "RealInstructionRuntimeState",
    "RuntimeDecisionJsonlWriter",
    "RuntimeReadiness",
    "SysNavInstructionRuntime",
    "SysNavSemanticMapBridge",
    "ViewpointEvidenceLoop",
    "WaitInstructionPolicy",
    "runtime_decision_to_dict",
]
